### ISSUE TITLE
create a devops philosophy slide

### ISSUE THREAD

**Issue by springdo** [sammarland/bluemix-devops-presentation#10]
Idea would be to introduce ideas of how to handle failed builds, and not leave builds failing overnight as it blocks others. Could bring the pink cowboy hat for cowboy committers!

**Comment by springdo** [comment]
Done!

**Comment by sammarland** [comment]
@springdo have you pushed your changes? I can't see this on Master? If you haven't can you rebase your changes on top of mine?

**Comment by sammarland** [comment]
Also if it's done can you close the issue?

**Comment by sammarland** [comment]
Just seen your branch. :smiley:
