### ISSUE TITLE
More ops side of DevOps - Kenny Loggins

### ISSUE THREAD

**Issue by sammarland** [sammarland/bluemix-devops-presentation#15]
Shall we mention Kenny slack integration? Could be a light hearted thing where we actually play a clip of the song - ask who knows the artist and then talk for 30 seconds about it?

**Comment by sammarland** [comment]
Let me know if you think this is a good idea and where it'd fit then we can work out getting the video in etc.

**Comment by springdo** [comment]
Yeah ! for sure!
Lets do it! Maybe more on the ops side of things? after the philosophy bit?

**Comment by sammarland** [comment]
The video is now in. Bit of debate with @springdo as to whether it should be a longer version or not so I'm going to cut another version and we'll test.
