### ISSUE TITLE
Talk about NodeRED (some IoT) in the Bluemix section

### ISSUE THREAD

**Issue by springdo** [sammarland/bluemix-devops-presentation#3]

**Comment by sammarland** [comment]
We need to think about how we present this so it doesn't become confusing.

**Comment by springdo** [comment]
Yeah agreed - maybe we could think of presenting it as just a what can be achieved with Bluemix? Or maybe I'll see if there are simple flow examples on the web. The Thermostat IoT is an obvious choice?

**Comment by sammarland** [comment]
Yeah. Maybe we can tie this back to how it applies to projects.

**Comment by springdo** [comment]
I just found this easy flow - might be good; ties into social. It's an auto tweeter flow. We can just use it as a 'this is what can be done'? http://thethingbox.io/docs/images/node-red_example/example-tweet/final_twitter.png

**Comment by springdo** [comment]
Actually - on the twitter stuff in node red.... we could say we have a flow for auto tweeting after having low wifi speed tests. that would be a good believable  home automation story that ties into bluemix

**Comment by springdo** [comment]
Added slide for NodeRED and home automation flow

**Comment by springdo** [comment]
Done!
